clang++ CPPBot.cpp enet/callbacks.c enet/compress.c enet/host.c enet/list.c enet/packet.c enet/peer.c enet/protocol.c enet/unix.c -pthread -std=c++11 -fpermissive -o buatid -w #Build source code into executableecho ""
echo "================================="
echo "⚠This Script Remaked By Mymet Code⚠"
echo ""
echo "Tool CID Successfully Builded,"
echo ""
echo "Kamu bisa ketik ./buatid sekarang!!!"
echo " "
echo "|Remaked By Mymet Code|"
echo "================================="
